### ISSUE TITLE
District field

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#16]
You suggested a district field for sorting results by district as well as course code. 
I can do this by creating a lookuptable for clubs and districts I think and this should be fairly efficient. Clearly it may change but I can update it with every full run (? weekly)
Do you want a district column in the rider DB or would you rather have a seperate DB with clubs and districts in, incase the rider changes club and we want to use the old district for their old results?

**Comment by rogernclarke** [comment]
What I had in mind is what I presume the CTT rankings page does - I think their district filter filters based on a rider's current club's district. It is just so that you can filter down to a list of riders that you would mostly recognise from your local events. Obviously some local riders who race for clubs in other districts would be missing but most would be there (although maybe we are unusual here in having a well-defined district with few events on the boundaries - may be very different further south!)

On that basis it would be sufficient to match current club to district on each processing run and update a district column held on the riders table. If they move to a club in a  different district then they have moved district and i don't think anyone would worry about their history being for a different district.

To make this robust you would have to start (as you suggest) by updating your lookup table of clubs and districts before processing the results as matching by the club name is dependent on any editing done to club names on the CTT site.

It looks like CTT have an id for each district. I was about to suggest we go with the district letter that is on the courses but have just discovered there is a National district for club affiliation (district id 23) and I'm not sure that has a letter code. We don't have to stick to a single letter so could just put "National" in for those riders (I wasn't thinking of storing the district name for all riders to save space, but maybe that is insignificant).

I'll add a district table with the letter and district name but it won't need any updating - will just be used for the dropdown filter choices.

**Comment by drnickw** [comment]
Resolved I think?

**Comment by rogernclarke** [comment]
Yes, closed
