### ISSUE TITLE
Rules for current rank

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#22]
I'll need to know the rules for which rides count for the current rank so that I can display just those rides when you click the button next to a rider in the rankings list. At present it is showing all rides in descending ranking points order which is clearly wrong and shows rides that don't count towards the current rank.

I need to know the last x many rides that can be considered and which ones of those will be excluded. Thinking to display all of the last x rides and then visually show which ones are discounted, maybe with a strike through or faded out. I'll also need to know the time period beyond which we drop rides.

I think we may need an extra column in rider history to indicate if a rider has a full or provisional ranking? I can then use that value to display appropriately.

**Comment by drnickw** [comment]
Hi Roger,
I think the "points" column on the events result page is confusing. I suspect its showing the nearly random numbers I generated for the events but I need to change them to the real scores for each race, which are sequential and only came out this week. I`m guessing that will be an update mysql command which I havent worked on yet. Racers will always have a lower score than everyone they beat in an event.
The rules :- Only races in last 12 months count.
Currently average score of first 3 events.
4 to 8 events - average of middle 2-6 (ie dropping best and worst)
More than 8 - average of middle 6 of last 8 (ie most recent).....
unless  you have > 8 within the last 4 months in which case you get the average of the best 7 minus the very best one. To reward people who have lots of current races.
I hope this makes sense. Its a bit arbitrary and I`m happy to review / open to suggestions.
I have a code I`ve been using which is letter-number-number. 
the letter is P for Provisional (< 6 events in 1 year) or C for complete (6+ events) or F for full (you now have > 8 in last 4 months and are getting this benefit) The numbers are the number of races in 1 year and in 4 months. So, it starts with everyone on P-1-1 and after P-5-5 you go to C-6-6 but i have riders on eg F-22-13 (Stuart Travis).
There is at least one glitch I`d be happy for your thoughts on. In the new year you have lost your 4 month benefits and your first ride tends to pull you back a bit as riders who havent ridden yet retain their enhanced score from last year. I could just retain your old rank so long as your score from the event is at least as good (quick fix).
Alternatively we could ignore winter months (Oct to Feb inc) but the recent race benefits would seem inappropriate in this circumstance.
I`m still fine tuning the points you get for a win.

**Comment by drnickw** [comment]
Hi Roger,
I`ve put a FAQ on the TV shared folder. I hope it explains the scoring better. You may feel its still unnecessary to have an F category but I think it adds something to work towards and there should be a big difference between someone who rides an event every 2 months and would be complete and someone who is riding every week. I think if you are riding that often your form is better reflected by your 6 best rides in the last 4 months rather than you last 6 rides, which is the difference between the two.
I will update the db in the next few days as the old data has clearly been superseded.
I thought it would be helpful to write the FAQ for our benefit whilst we are developing the system as it gives you a better understanding of what I have been doing and also I would be interested to see some info on the functionality you have been developing too. I`m not suggesting this is a final draught or even that all the FAQs would necessarily want to be published. The one about "20s" may be going too far but its a reality I had to contend with to manage top end rides (and by far not the most complex - i`ll not go into the details of ratios of standard deviations) and I`m sure people will wonder. I`d like to make it as transparent as possible without totally bamboozling people.
If I`m honest we could probably include the best ride too for everyone outside the top 100 as once you get away from the extreme range the scoring is extremely stable, but I`m not sure people would understand if I only excluded their best ride if they were a big hitter. The bit about the weather changing is true though for everyone.

**Comment by rogernclarke** [comment]
I have added a column to the rides table called counting_ride_ind as a boolean, so you have to set it to either true or false. It is a mandatory column so any updates you write to the table from now will need it to be set.

I have also added a column to the rider_history table called ranking_status. I can't think why we would want to display the number element to e.g. p-1-1, so shall we just go with the letter? I think letter rather than text description as we want to keep the rider_history table as small as possible.

**Comment by rogernclarke** [comment]
I've had a read of the FAQs - really good! I still think we need to tweak the wording about the counting rides as this is one that everyone is going to want to understand. Maybe we could add two or three examples of riders in different circumstances and show which rides count.

**Comment by rogernclarke** [comment]
I think that all that is needed to complete this one now is for the counting_ride_ind on the rides table to be populated. Check out Marcin's rides in the ranking list. I will likely change the styling for non-counting rides but that is a minor tweak.

**Comment by drnickw** [comment]
I had done this but I passed "y" and "n"  and this clearly didnt work. 
I`ve tried passing logical TRUE and FALSE and 0 and 1 but this doesnt seem to work either. 
What is needed for the DB to recognise it?

**Comment by drnickw** [comment]
Got it working with 0/1 but clearly I havent got the processing right. I`m sure the numbers are correct but the indicator isnt properly assigned. I`ll look into it

**Comment by drnickw** [comment]
Sorted now BUT i think its very confusing on the website - see Colin Ward. Its right cos 6th June is > 4 months before my 8.10.18 run date but it looks weird. May be better to sort by date than score.

**Comment by rogernclarke** [comment]
I will play around with ordering rides - assigning to me as I think it is all display related now.

**Comment by rogernclarke** [comment]
Check out the order of rides within the rankings list. Think it is correct on my side with a clever bit of SQL. The only oddity I know about is the question I asked yesterday about whether you can always discount the oldest ride if there is a tie in scores for fastest and slowest rides being discounted. See Harry Tanfield and Adam Duggleby. Or in fact several other riders in the top 10 men.

I see you have changed the rank for those who look like they have the same score. It won't make much difference for people lower down the rankings but it is fairly obvious in the top 10 that some should be ahead of others if there was a decimal place. I wonder if that would raise questions...

**Comment by drnickw** [comment]
The order is due to decimals for the counting rides - i can change it to keep newest rides when i do the next run. However looks right for Duggleby but strange on the site?
I`m not sure a decimal is enough to split these riders and within the data we are presenting it looks right on the front screen but I agree if you click on the counting rides you can see the difference. I`m happy to switch it to exact matches only - will probably only ever happen on 20 in that case. Could add 1 decimal to scores < 100 but may look a bit messy on the front page and confusing from 99.x to 100.

**Comment by rogernclarke** [comment]
Ok, looks like I have another more tweak to make on the ordering now to make sure that the discounted top score is always at the top of the list. Going to come back to this another time so note for myself here to union the lowest discounted score with the rest of the rides to be shown.

Not sure what you mean by exact matches only. I had thought about adding a decimal for those scoring <100 but the column is currently set as an integer, so whole numbers only. I think people would understand the rounding errors if we left it as an integer but ranked on the decimals. FAQs could cover it. Will only be obvious for the top few riders with 20 scores.

**Comment by drnickw** [comment]
exact as in score will be exactly the same - will just about never happen except around 20 so there will be lots of instances lower down the ranks where riders have the same rounded score but will never be given joint rank or necessarily same category as the decimals will be off.

**Comment by drnickw** [comment]
Good spot. Thanks for that little puzzle.
It applies to riders on a C with fewer than 9 rides.
Code was [2:raceNo-1]
Should have been [2:(raceNo-1)]
It took the 1 off both the raceNo and the 2, so made the 2 into a 1 thereby
giving us the highest score!
The scores were correct but not the counting ride indicator.

**Comment by rogernclarke** [comment]
Closing this one - all the counting rides look good now
