### ISSUE TITLE
Initial data load

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#26]
We will need to do a "grand run" as you call it when we are ready to populate our live database.

My preference would be to do simulated weekly updates (rider history record having an appropriate date for the week it should have been run) for the whole of the 2018 season so that we have a rider history record weekly for each rider following the week of their first ride.

Presumably we stop producing a history record for a rider once they have no rides within the last 12 months? Do they need a final record which shows that they have no rank? Not sure what that record would look like off the top of my head.

Should we just start rider history records from 1/1/18? Do you think people would want to look at them for 2017? Are rankings accurate enough from the start of 2017?

**Comment by drnickw** [comment]
I think people will be more interested in the effect their races have on their rank/cat, rather than seeing a weekly slow degredation of their score when they dont ride. Do you think we could have a graph for each on the rider page showing rank or score or cat on the y and date on the x, with the events ridden given a bar upto the line?
I`d be inclined to start from 2018 for the weeklies as I cant exclude rides based on time in the first few months anyway as i dont have enough data till lots have ridden, although I do have my primer rankings.

**Comment by drnickw** [comment]
Record with code set to L for lapsed. 
Programming done for this.
Takes <3 mins per week so a year is about 2.5 hrs runtime!

**Comment by rogernclarke** [comment]
I think that's quite quick for a PC given what it is doing in total!

**Comment by rogernclarke** [comment]
I think you have done the "grand run" from your side? Shall we close this one and I'll email you live database connection details once it is set up?

**Comment by drnickw** [comment]
Happy to close now. Only producing records once for lapsed riders then they go into hibernation.
Have managed to improve the code and can now do a week in 1m45 secs so not quite such a big job but still over an hour to load 9 months data. Still should never need to be repeated.
