### ISSUE TITLE
Going live

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#29]
I`ve been looking at the latest TTF stuff. I suspect its only a minority but its in the public eye again. The ELO system is the best bar ours. Our advantage is ranking using time as well as who you beat so we can give rewards for Marcin beating the field by 5 mins which ELO cannot.
I was delighted with the results of the 50, Adam was running it down as I was wrong about him, but as I said I hadnt updated since mid August or adjusted for trends. He beat 3 people I wouldnt have expected and 1 rider, who should have beaten Adam clearly had a bad ride. However if you look at the top 10 i got 1,8 and 9 spot on and 2-7 right but in the wrong order but if you look at the scores they were all within 6 points and well clear of 1st and 8th so in the correct grouping. I think our results speak for themselves.
The issues they raise on TTF are all addressed by us, except for the KISS, and with some careful work on the FAQ I think we can jut about resolve this. You cant have KISS and accuracy.
Whilst Steve Lockwood could put together an ELO system very quickly, the Midland system seems to have a very slow response time so I suspect its unlikely, and the work you`ve done on the database is not going to be reproduced any time soon, and that is our other trump card. If someone did ELO and a nice website I think we`d have trouble getting our system into first place if we went live after them.
I`m starting to wonder what it will take for us to go live soon, and how many features we need. I`m sure we wont get the individual comparisons for a while, or a user matching system for neg CTT numbers.
If we can do a weekly run for 2018 and show counting events how far are we from a live date. Is it worth spending time now on District codes and tidying names? Alternatively we carry on working steadilty and bring it out all singing and dancing in Feb?
I`m on holiday next week from work and should have some time again, although if the weathers good I may have a few days in Scotland.

**Comment by rogernclarke** [comment]
Yes, I had been reading the posts - a shame we weren't ready to go right then!

I was somewhat amused that one person completely disregarded ELO just because he didn't understand the maths behind it.

I think we should try to bring our release forward to as soon as possible. Steve Lockwood seems to be the risk, and whilst his web design / build is poor, the difference between your calculations and whatever he comes up with may not be sufficient in terms of ranking outcome to persuade people to leave what he produces as it should be quite a lot better than the current CTT rankings.

I think we need to focus on the minimum we need to get live with a small set of functionality but what we have to work really well.

I'll set up the project board on our github project to have Release 1 and Release 2 so we can assign all essential issues for going live into release 1, and anything else to release 2. If all the issues are then assigned to one of us then we can work on completing release 1 and ignore anything else. If we then agree on what has to be in release 1 we will have our work list set out.

On the list for me would be:
- Initial load of weekly calculations for 2018
- Identify counting events
- Rider districts for filtering
- Ranking by gender
- Display of provisional / complete status
- Additional info on rider profile page e.g. category, highest category, highest rank etc.
- FAQs
- Homepage design
- Contact details / form
- Stopping bots from indexing all links on website

That won't be an exhaustive list.

The only downside of going early is that I won't be able to use our live website for development of further functionality, but there are ways around that.

**Comment by rogernclarke** [comment]
Closing this issue as we've either built all the suggestions or they are covered by other issues
