### ISSUE TITLE
Error in results for an event

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#32]
Check out first place:
https://www.spindata.co.uk/rankings?task=event.display&cid=17562

Looks like hours and minutes have been transposed into minutes and seconds! I imagine this is just an example of the issues you have been facing.

**Comment by drnickw** [comment]
I need to follow this up. I`ll have to re run the scoring once I`ve corrected the data. they must have entered it in a valid way or i would have picked it up. Need to consider this for the future and flag any obviously extraneous results before we go to DB for manual adjustment.

**Comment by drnickw** [comment]
The problem is she was the only rider over 1 hr and happened to finish on a :00.
If all the results in a race finish in :00 (and whoever entered the results put everyone else on 5x:xx:00)
then the program assumes the last :00 is hundredths and bins them. Rather than trying to make a code just for this incredible one off, I`ve added 1 second to her time which makes it work. Dont tell anyone!
