### ISSUE TITLE
Confirm Form Resubmission

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#34]
Error when trying to go back to rankings with Prov box ticked

**Comment by rogernclarke** [comment]
The reason this is happening is because the filters for the lists are being submitted with a POST instead of a GET. Making some notes here to revisit later.

There are potentially two ways to fix this...

1. Rewrite the form submission changing the POST to a GET (see https://stackoverflow.com/questions/22710332/joomla-3-2-submit-form-via-get-method-to-a-view and https://stackoverflow.com/questions/18959813/joomla-2-5-form-redirection-error/18960103#18960103)
2. Use a POST and redirect to a task (see https://forum.joomla.org/viewtopic.php?t=953929)

**Comment by rogernclarke** [comment]
I've just noticed something interesting with this - if you put some filter details in on a list and then click through to a rider, clicking back gives the error. If instead of clicking back you choose the menu option at the top to take you to the list you get no error and the list is filtered correctly. Not sure if that helps me though!

**Comment by rogernclarke** [comment]
I think I have fixed this on dev - do you want to see if you can break it?

**Comment by drnickw** [comment]
I’ll try.
Check the predicted zeros.
