### ISSUE TITLE
multiple same riders

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#38]
Seems when I upload the riders hx db we get multiple entries in the riders db?

**Comment by rogernclarke** [comment]
I saw the effect of this but it isn't showing like that now. Have you changed something with the data since you raised this?

I found a bug in my data selection when it was wrong last week, but it should work fine as it is now.

**Comment by rogernclarke** [comment]
The original bug was because I have to join the riders table with the rider history table and it was joining each rider to each of their rider history records, producing 9 records for each rider in total. I changed the SQL query to stop that, but I can't think why it came back, unless I somehow temporarily broke the query whilst doing something else. Let's just leave this issue open for now and keep an eye on it.

**Comment by rogernclarke** [comment]
I think it is safe to close this one after another successful data load
