### ISSUE TITLE
Improved rank - Antelope RT

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#51]
Looking at the event results for the Antelope RT on 28th October - Kirsty Mcseveney has got a -16, for 18th place, yet her points for her ride represent her best ride of the year by a country mile. Something doesn't look right. Ditto for Michelle Walter in the same event.

**Comment by drnickw** [comment]
I`ll take a look.
The movement on position is giving me all sorts of confusion.
Missing out non counting riders seems right if you keep your position but
not if you improve or reduce it. Its not as easy as I thought to reconcile
the before and after.
This may not be the problem here however. I`ve clearly got a bit more work
to do.
Any anomalies gladly received - as I say its the website now which shows
these best.
Still, the end is in site now I think.
Nick

**Comment by drnickw** [comment]
had a quick look in my lunch break.
weirdly the right hand columns in the output have been transposed 1 place
down!
should be easy to fix once I find out why. all the data is correct just out
of place.
the tt_races file on the shared folder has it right. not sure how it got
corrupted in transmission.
I`ll track it down.

**Comment by rogernclarke** [comment]
Looks good now
