### ISSUE TITLE
Display of ranks on rider screen

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#69]
Add current age category and district ranks to top right hand side of rider screen.
Add icon for gender in front of rank.

**Comment by drnickw** [comment]
Think we`ve got this now, unless you want to re order?

**Comment by rogernclarke** [comment]
I'm in two minds on this one.

I think for women it is right that gender rank comes top.
But it would flow better with overall rank top.
Four choices I can think of:
- Put overall rank top
- Put gender rank top
- Put overall rank in brackets or grey it out a bit so it is shown not to be so important.
- Remove overall rank altogether - is it that relevant?

**Comment by drnickw** [comment]
I wonder how it would look if you put the overall next to the cat tag above
the line (as the cat tag is dependent on the overall, and keep the others
below the line. May not look as neat but might make sense.
I`m inclined to have them in descending order which is why i would put
district below age cat as this is more likely to be descending order (but
probably not always).

**Comment by rogernclarke** [comment]
Putting the top two rankings next to each other will only work for a laptop sized screen... if you drag the side of your browser window in to make it much narrower you'll see what happens when the club name starts to bump into the ranks on the right. With a much wider ranking text it would bump into the other text much sooner. It would also break onto two or even three lines in its own right much sooner.

I wouldn't like to guess if district or age rank was likely to be lower or higher but I have no preference on those so I'll move the age category higher. I'll have a play with the options on rank and overall rank and we can see which we prefer.

**Comment by drnickw** [comment]
I was thinking above the line, next to the cat tag, not the 2 rankings on
the same line. Would bump into the name eventually?

**Comment by rogernclarke** [comment]
Oh, sorry, I misread. I still don't think that would work though, plus it would suggest that overall rank is more important than gender rank.

I'll try some different things, take screenshots, and add them on here so we can choose from the options we have.

**Comment by rogernclarke** [comment]
Option 1:
![tablet_layout1](https://user-images.githubusercontent.com/10092388/49888221-4be83b80-fe36-11e8-89ae-e2144f245432.png)
![phone_layout1](https://user-images.githubusercontent.com/10092388/49888223-4ee32c00-fe36-11e8-8d3a-545e18e9fa93.png)
Option 2:
![phone_layout2](https://user-images.githubusercontent.com/10092388/49888232-53a7e000-fe36-11e8-9981-5d94b5259af7.png)
![tablet_layout2](https://user-images.githubusercontent.com/10092388/49888237-56a2d080-fe36-11e8-8764-8d65195a46be.png)
Option 3:
![tablet_layout3](https://user-images.githubusercontent.com/10092388/49888243-5c001b00-fe36-11e8-91b1-55f9bf460664.png)
![phone_layout3](https://user-images.githubusercontent.com/10092388/49888251-5f93a200-fe36-11e8-8f87-f5f5ee88445d.png)

**Comment by drnickw** [comment]
Of the 3 I think I prefer option 3. Just feels like the right order.
I can see if we move the overall above the line to the left of the cat tag
it will potentially clash with the name on a small screen.
Option 3 doesnt emphasize the overall but it keeps it close to the cat
(which is entirely dependent on it, rather than on the gender rank).
I guess the only way it could be above the line would be to swap it with
the rider status tag, or possibly move this tag somewhere else. If it was
in a small font and grey it wouldnt detract from the gender rank.

I`ve read your spindata posts on TTF with interest. Nice one responding to
the thread.
I`m still amazed that people describe exactly what we offer when they list
the things they want out of a system yet somehow dont seem to be able to
see we provide it.
Certainly the new emphasis on categories should be well recieved, its just
a pity they didnt notice this before!
I think we will generate some more positive reviews when we put v1.1 out
and hopefully show how interactive we can be (especially compared to the
CTT response rate to their enquirers)

**Comment by rogernclarke** [comment]
Option 3 was my preferred option as well so I have left that in place. I'll close this issue now then.
I had the same feelings about the TTF posts. We did score a victory when someone said he would just use our system though!
