### ISSUE TITLE
Timing of website data updates

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#90]
System was designed for a single weekly load of results / rankings / startsheets. This can accommodate late startsheets being added but otherwise breaks down on consistency across the app.

Need to review whether to stick with a single weekly update or to make changes to allow for quicker posting of results. Also, is it a good idea to do early race predictions and update later or just issue a single prediction nearer the time - will people check back if they have already seen the prediction?

**Comment by drnickw** [comment]
I would be keen to see events "above the line", ie events which have predictions but havent been run yet and events which have been scored but havent been added to the weekly ranking update, showing on the rider page under Pending or some such heading. It would be good to be able to see which events someone has entered as currently its not possible to find out if someone is on a startsheet I dont think. Also we are moving it seems to a steady hit rate through the week rather than a surge mid week and people are keen to see how many points they`ve scored asap. It would be easy for me to score events early and still  process rankings just once a week.
WRT the startsheets going out 2 weeks early, people are obviously interested in getting this info asap and seem to understand it will be updated next week and appreciate this, from the feedback ive had.

**Comment by rogernclarke** [comment]
Think we need to have a get together once the awards have gone live and work out what we work on next...
