### ISSUE TITLE
Add Form indicator to rides

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#91]
Display a Form indicator against rides on event and rider screens to show when a rider has exceeded their predicted placing in two or more consecutive events

**Comment by rogernclarke** [comment]
I've added a new column called form to the rides table. It is a tiny integer so that should cover values up to 127!

**Comment by drnickw** [comment]
Ok, thanks.
I`m still playing with the best way to fill it.
One issue will be if a rider rides sat and sun with form and his sat result
is delayed till after the weekly run. the form will end up reversed once
the rides are sorted by date. I think I might need to work out the last few
forms each time.

**Comment by drnickw** [comment]
Done on Dev.
Turns out form I had in mind (ie number of races you beat your
prediction)has virtually no predictive value at all.
Tried the multiplier but this wasnt that good either.
In the end the simple "progress" was best - defined as total number of
places gained over the recent consecutive events you`ve ridden with gains.

I`ve split it into 6 bands - ie form 1-6. so 127 is plenty.

Something really weird wit the ctt numbers though.
I looked at predictive value and if you`re on a max form ie 6 you`re twice
as likely to beat the prediction next race as you are to loose or draw (ie
match prediction). I`m calling this 200%
This is far and away the best I can do here, I`ve tried loads of other data
manipulations.
However, this is true for the riders from ctt number 14875 to the end (on
average)
If you look at the earlier numbers its closer to 150%
And for a form of 1 it ranges from 110% for low ctt number riders to 130%
for the over 14875s.
Can you think of any differences that might exist between the 2
populations? I`m not sure how they allocate the ctt numbers.

**Comment by drnickw** [comment]
Do you think its worth putting in all the historic form?

**Comment by drnickw** [comment]
Should we have a latest_form on the rider table too or are you going to
pick it up from the last in date ride?

To simplify processing, I`m allowing a run of form for a max of 4 months,
ie if you have improved for every event in the last 4 months all those
events will count for your form score.
4 months is because I already process a group of last 4 months rides for
checking frequent status so its easy to add the processing in there.
I agree however that form per se shouldnt last beyond 4 weeks, so once
you`ve had a 4 week gap we can clear the form, BUT if you then rode again
and again beat your prediction your old form (within 4/12) would come back
as it were.
I think that`s OK as clearly you have proved you`ve retained that form.
Other thing is form doesnt wane. Whilst you are accruing it you can move up
the form ladder but if you have a less good but still prediction beating
race your form will stay high.
I did try modeling the data using just the last few races of a run of form
to see if that was more valid but it seems not.
I think its because you are still essentially catching up with your self
ranking wise. Once you get back onto a ranking level then obviously your
form disappears.  (or at least the meaning of it in Spindata terms)

**Comment by rogernclarke** [comment]
CTT rider numbers were / are issued in the sequence of riders registering on the CTT site. So lower numbers will generally be for riders who have been racing longer than the higher numbers. The obvious thought on that is that the lower numbers are for riders who are more likely to already have hit their peak performance whilst new riders to the sport will have higher numbers and therefore have more potential to improve?

**Comment by rogernclarke** [comment]
I think we should only calculate and load the form from the start of this year. I assume you will restart the form calculation at the start of each year and exclude Xmas events?

**Comment by rogernclarke** [comment]
I'm having some doubts about how we are determining form.

A rider who is predicted to win a race has no chance of beating their predicted place, so can't be considered to have good form no matter how much be might have improved on previous performances. part of this could be down to the luck (or bad luck) of not having a better rider entered in the event. So I started thinking that maybe we need to count rides where predicted placing has been exceeded or matched.

That got me thinking further that riders in small field events have less chance of beating their predicted placing than in a full field event where there is more chance of there being riders ranked only slightly higher. The top women would also have more chance of being on form because there is more chance of having male riders ranked slightly higher than them in the field.

Given that the beauty of the Spindata system is that it is entirely neutral in terms of course ridden or weather conditions or gender or field size / make-up, why wouldn't we use the rider's consecutive run of rides scoring less than their ranking score to determine whether they are on a streak of improved form?

**Comment by rogernclarke** [comment]
Is the form value against a ride the form before the ride or the form after a ride? Do we need both? Thinking form before on the event startsheet and results, form after on rider screen list of results?

**Comment by drnickw** [comment]
Now I`ve set up a system for assessing the predictive value of different
data I can do a run looking at consecutive improvements in scores to see if
this is a valuable indicator of form too, and how it compares with the
validity of the positions improved version. I can see that the positions
improved system will deny some people their form. maybe a bit more work to
do here. I`m still keen to get some kind of form system working as we know
some people are likely to beat their predictions and it would be good to
acknowledge this without amending the predictions themselves.

Agree startsheet form is clearly pre ride form, which would be the form
from after the last ride. So we only need 1 form as it wont change until
another result comes in, but it could lapse, which is why I`d need to amend
it on the riders page with each run if I do it, or you`d need to check it
against the date if you do it. we can have pre and post form on each ride
if you want, but pre form is just the form from the last ride so seems like
duplication, unless it makes the processing easier.

**Comment by rogernclarke** [comment]
I think we should see what it looks like on the list of rides before we decide if we show it at the top of the rider page.

I've added a crude version of the indicator to the start sheets - it is a flame icon in front of the rider name, but I don't like the icon so I'll look for a better one. There is scope for showing more than one flame but maybe 3 flames is the most we should go up to?

Not sure from comment above what we should show on the result sheet for the event. Do  we show the form on the ride record (i.e. the pre-race form indicator) or not show form as the result is in so it doesn't really matter?

The rides on the rider screen currently show post-ride data so thinking form on that list should be post-ride? I won't know what the post-ride form is unless you tell me will I?

**Comment by drnickw** [comment]
I like the flames or something along this line. Its a pity they push the
riders names out of sync and Im not sure it would work with more flames.
No problem cutting form to 3, we can just lump my indicators together.
perhaps they could be right aligned in the name field? Maybe they`re best
where they are.
Maybe its enough to just have a single form indicator, im not sure,
although I can prove that more indicators give a better likelihood of
success.

The event I looked at. Chippenham, everyone with form beat their
predictions so i think its valid and worthwhile.

Your suggestion for comparing points from a ride is pretty much the
"improved score indicator".
this compares the score rather than the rank but actually its pretty much
the same thing and in reality the points from a race are really scores
rather than ranks so im fine with that.
I suppress the detail before i send it to you by changing the number into a
1,0,-1 so I can easily keep the actual change rather than just the sign of
the change to give us more definition.

I`d like to spend some time looking at predictive values before we send
this in too. It may be worth using both metrics to pick up everyone with
form, although we dont want too many or it becomes meaningless.
I can raise the threshold if this becomes an issue.

Do you want to run with what we have this week or wait for more, there`s no
doubt what we are currently doing on dev is right, just may not be the full
story.

I think if we were going to show form on the results it would be to confirm
that our form predictions are in the main accurate and would need to be the
pre race form, but form on the rides screen should be post race form I
agree.
This might be confusing as if you lost form it would show form on the
results page but not on the rides page, althogh it would be consistent -
the cat changes between these 2 screens too, so may be OK.
Quite like the form on the results as my immediate assessment was to flick
between the 2 screens to see if form carried into the result, although that
may just be me checking up on myself. However cant see a good reason not to.

Happy to keep form off the rider page for now. could be for the future.

Form on the tt_ride table is currently post race form. The startsheets
would need me to add pre race form from the last ride if eligible.
This is not a problem, but if we want to use both we either need to keep
both on the tt_rides table or look up the last one when processing.

**Comment by drnickw** [comment]
Second paragraph may be optimistic thinking about it.
If you have associated the form on the ride table with the pre form for
that event then no wonder I did so well, its the post race figure Ive given
you.

**Comment by rogernclarke** [comment]
Haha - always helps with accuracy of predictions if you use the results as predictions!

My gut feeling on this is that we should have a pre-race form and post-race form for each ride (it is only one extra byte per record) purely on the basis that form can expire. If you own the whole of the processing for awarding and expiring form then we will always have a consistent set of data. I will sort that out in the database later and post here when I've done the change.

My suggestion would be that I will try out a few options for the location / number of flames and screenshot them for us to choose between. Once we've made the choice I can then release the changes to the app and you can populate the data whenever you are ready (I'll check it with a few records on dev). I can add a module of on form riders to the homepage at any time outside of the main app release process, so that could be done whilst we're working on awards - I can't really start on the awards until the current release goes live.

**Comment by rogernclarke** [comment]
I have changed the existing form column to be called post_ride_form and added a new column called pre_ride_form. Be aware that I have put the new pre_ride_form column before the post_ride_form column as that seems a bit more logical. I'll have to fix the app now to use the new column names...

**Comment by rogernclarke** [comment]
Take a look at the result sheet for event 18670. I think this is the best display we are going to get for the flames. I have gone with one or two flames - two flames if form is > 3. I haven't tried it after the name but I think it would get a bit lost there with the category being after the name as well. I'll add it to the rides on the rider page but after the event name.

**Comment by rogernclarke** [comment]
Oh, you'll need to clear your cache to see it correctly!

**Comment by drnickw** [comment]
I`ll check this out tomorrow. I need to sort out the errors from last week
tonight and then do the new run tomorrow night and I`m out till 9.30 so
we`d better put form on hold for this week.

**Comment by rogernclarke** [comment]
Closing this as form seems to be working fine just on events page.
